version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run serve
